[package]
name = "elven-tools-sft-minter"
version = "0.4.0"
authors = ["Julian Ä†wirko <julian.cwirko@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.43.3"

[dev-dependencies.multiversx-sc-scenario]
version = "0.43.3"
