[package]
name = "elven-tools-sft-minter-meta"
version = "0.3.0"
authors = ["Julian Ä†wirko <julian.cwirko@gmail.com>"]
edition = "2021"
publish = false

[dependencies.elven-tools-sft-minter]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.42.0"
